name: Datos GT

on:
    push
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Instalar Python 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Creating secret JSON
      env:
        TEXTO1: '{"twitter":{"token_acceso" : "'
        CODE1: ${{ secrets.TOKEN_ACCESO }}

        TEXTO2: '","secreto_token_acceso" : "'
        CODE2: ${{ secrets.SECRETO_TOKEN_ACCESO }}

        TEXTO3: '","clave_api" : "'
        CODE3: ${{ secrets.CLAVE_API }}

        TEXTO4: '","clave_secreta_api" : "'
        CODE4: ${{ secrets.CLAVE_SECRETA_API }}

        TEXTO5: '"},"correo":{"username" : "informaticasudaustral@gmail.com","password" : "Sud.Info91"}}'

      run: |
        echo $TEXTO1$CODE1$TEXTO2$CODE2$TEXTO3$CODE3$TEXTO4$CODE4$TEXTO5 > keys.json

        python Servidor.py

        rm keys.json

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Datos Guatemala"
        branch: master
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: hectorflores329@gmail.com
        commit_author: DataIntelligence BOT <hectorflores329@gmail.com>
        push_options: '--force'
